### ISSUE TITLE
Contact Section Bugs & Suggestions

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#11]
### Issue
- [x] Button Text changes don't reflect anywhere. The current button's label says "Subscribe" (might be a wrong copy/paste from the Subscribe panel?) and it's not showing anywhere on the front-end.
- [x] Changing zoom values throws an `Invalid Value' error. 

### Suggestions

I have a couple of suggestions on how this section could be improved:

- [x] Instead of having the link to get a Google Maps API key open in the same tab, maybe it'd be better to have it open in a new tab. This way, the user gets to keep the Customizer panel open. Currently, when I click on the link, it takes me straight to the Google Maps API Key section. 
- [x] Instead of asking for lat & long look into using a function that translates an address into actual lat & long coordinates. It's easier for users to paste in their address than deal with GPS coordinates.
- [x] Turn the zoom input text field into a range input field type. With a bit of CSS magic, you can turn it into something really friendly for the user. Also, this way, you'll be able to control the min & max values. 

Here's a few links that should help

- https://premium.wpmudev.org/blog/creating-custom-controls-wordpress-theme-customizer/ 
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/ 

I'd create a new custom control titled `{Theme_Prefix}_Range_Slider` and place it into a separate file. This way, you can reuse it across your projects.

**Comment by nicoandrade** [comment]
Fixed the issues.

**Comment by cristianraiber** [comment]
@nicoandrade - how about the suggestions ?

**Comment by cristianraiber** [comment]
@nicoandrade - the "Subscribe now" button isn't showing up anywhere in the contact section. 

![image](https://user-images.githubusercontent.com/7841556/30327922-799ca06a-97d6-11e7-931c-d0500d8d95cf.png)

**Comment by nicoandrade** [comment]
I removed that option, it was an old implementation.
About the suggestions, will not be implemented.

**Comment by cristianraiber** [comment]
@giucu91 - I've edited my first ticket and turned this into a to-do list. Mark the items once you're done with them, please.
