### ISSUE TITLE
Background Image control doesn't do anything

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#12]
Most likely, it controls the background image somewhere for the blog, but that's not obvious in any way.

**Comment by nicoandrade** [comment]
It is working but remember that the modules with a particular background are overwriting the global background.
On the rest you can see the background image.

**Comment by cristianraiber** [comment]
@nicoandrade - it does seem to work, although the design decision is very weird. Am marking this as closed.
