### ISSUE TITLE
No proper logo handling

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#13]
While you're offering a crop value for your images, in the logo, I can still upload any type of logo size I want. The way I usually handle this is by forcing the image to be a certain size by combining two techniques:

- using `add_image_size` and defining a custom one
- forcing the logo to be a certain size with CSS

**Comment by nicoandrade** [comment]
I'm not sure about this one. I prefer that the user can use any size he want. Logos can be so different bewtween one and other.

**Comment by cristianraiber** [comment]
Users should be instructed about the proper logo size. You should never let them upload the size they want. This causes a lot of problems with: HiDPI logos, respecting the template's design as well as logo crispiness on mobile devices. 

What I wrote above wasn't an advice, but a request. Please implement it in that way.

**Comment by nicoandrade** [comment]
I don't think the user should be forced to use a certain size for the logo. That will be assuming a lot on our end.
Also the default way that _S theme handles the logo is the same:
https://github.com/Automattic/_s/blob/master/header.php#L30

**Comment by cristianraiber** [comment]
`_s` isn't a de-facto standard of good practices. It's just a starting example. Remember: decisions, not options. When faced with multiple options, users will most likely pick the worst ones and blame the theme developer. 

@puikinsh - We'll address this in a future iteration, np.

**Comment by nicoandrade** [comment]
Yes, exactly. This is subjective, there is no right or wrong approach. 
I see your point and is 100% valid but for me logos are different from any other image, and the user usually is sentimental about the size, that's why I think this way.

**Comment by cristianraiber** [comment]
This was added: https://github.com/puikinsh/bonkers/blob/master/functions.php#L109

**Comment by cristianraiber** [comment]
@giucu91 - I've re-opened this as per our Slack chat. Let's add the Shapely logo control in here as well.

@puikinsh - more info, here: https://github.com/puikinsh/shapely/issues/158
