### ISSUE TITLE
Console log errors

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#14]
![image](https://user-images.githubusercontent.com/7841556/30166008-df294f4e-9396-11e7-97cd-ba4aefa17894.png)

**Comment by nicoandrade** [comment]
Fixed

**Comment by cristianraiber** [comment]
@nicoandrade - this doesn't seem to be fixed.

![image](https://user-images.githubusercontent.com/7841556/30327775-f390d982-97d5-11e7-82cd-03e939f81646.png)

**Comment by nicoandrade** [comment]
Done

**Comment by cristianraiber** [comment]
@giucu91 - can you please test this, make sure those errors are gone?

**Comment by cristianraiber** [comment]
@giucu91 - please see this: https://files.slack.com/files-pri/T0HLN2J90-F7J6WGVBJ/pasted_image_at_2017_10_16_04_20_pm.png
