### ISSUE TITLE
Replace all unsplash.com images

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#15]
@nicoandrade - Unsplash has recently changed their policy and their images are no longer GPL compliant. Please, replace them and also readme.txt.

**Comment by nicoandrade** [comment]
Done

**Comment by cristianraiber** [comment]
@nicoandrade - Pixabay images are not fine either. They've also changed their licensing. Please replace image with MIT / GPL2/3 or CC0 images.

Thank you!

**Comment by nicoandrade** [comment]
@cristianraiber on their site says:

> All images and videos on Pixabay are released under the Creative Commons CC0.
https://pixabay.com/en/service/terms/

**Comment by cristianraiber** [comment]
@nicoandrade 

Even the first image you used, from Pixabay, was uploaded less than 1 month ago. 

Below screenshot is taken straight from #themereview channel on Slack

Please, fix the images. 
--- 

![image](https://user-images.githubusercontent.com/7841556/31124084-8b905d68-a84b-11e7-8b69-86e90cb90e6a.png)

**Comment by cristianraiber** [comment]
It would like that only 1 of the images you've used would qualify per the TRT rules.

**Comment by nicoandrade** [comment]
Images updated:
Images from StockSnap.io
License: https://stocksnap.io/license
https://stocksnap.io/photo/1A3MXAT0M6
https://stocksnap.io/photo/JBW2PXDOL6
https://stocksnap.io/photo/R7GVMRJWW9

Images from pixabay (**prior to Jul 27, 2017**)
License: https://pixabay.com/es/service/terms/#usage
https://pixabay.com/photo-1274360/
https://pixabay.com/photo-1690965/

**Comment by cristianraiber** [comment]
Thank you @nicoandrade for the fast response.

**Comment by nicoandrade** [comment]
Thank you @cristianraiber 
This last update also updated the Bonker's plugin:
https://cl.ly/2p1d3j3e3J1l

**Comment by giucu91** [comment]
Hello @nicoandrade ,

Can you please tell us from where did you get the images for services ( 48.Dashboard.png, 30.User.png, 03.Office.png ) and the iPhone mockup ( phone_bck.png ). I didn't find these images in the readme.txt

Have a nice day,
George.

**Comment by cristianraiber** [comment]
@nicoandrade - please reply

**Comment by nicoandrade** [comment]
Hi guys I'm sorry for the delay.
iPhone Mockup is made by me, I'm not sure if I have to add something in the readme.

Icons are from here:
https://dribbble.com/shots/1569128-Freebie-48-Bubbles-Iconset
It simple says: 

> Feel free to use however you wish.
