### ISSUE TITLE
Custom Image Controls should be used, so you can provide the "default" image

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#2]
Currently, all background images are harcoded. If a user goes into the "header" section, changes the image, but decides to revert instead of providing the default WP functions of clicking on a "Default" button, the user has to delete his image.

Also, this is against TRT rules.

**Comment by nicoandrade** [comment]
The"header" section is using the default custom_header function from WordPress, I don't not what you mean exactly there.

But if we take, for example, the "Welcome" section. There is a default images as part of the design of the site, if the user want can change that without problem.
That's not against TRT is commonly used.

**Comment by cristianraiber** [comment]
@nicoandrade - as previously stated, you shoud use a custom control to handle this. If you'd take a look at how WP Core handles the `Default` setting on their image upload fields, you'd understand better what I'm saying.

Here's how we're doing it: 

```
$wp_customize->add_setting( 'pixova_lite_testimonial_1_person_image', array(
    'sanitize_callback' => 'pixova_lite_sanitize_file_url',
    'default' => get_template_directory_uri() . '/layout/images/testimonials/teammembru_burned-92x92.jpg',
) );
$wp_customize->add_control( new WP_Customize_Upload_Control ( $wp_customize, 'pixova_lite_testimonial_1_person_image', array(
    'label'     => esc_html__( 'Testimonial person image', 'pixova-lite' ),
    'section'   => 'pixova_lite_testimonial_1',
    'priority'  => 3,
) ) );
```

----

Here's how core's handling it.

Code:
https://github.com/Automattic/_s/blob/master/functions.php#L62-L66

---

We basically took the code from core, created our own custom control and reused it, where deemed appropriate. You should do the same.

**Comment by nicoandrade** [comment]
Ohh ok I see what you mean now.
I updated the code to support the 'default' field :)

**Comment by cristianraiber** [comment]
@nicoandrade - please don't close tickets before letting me test them. Also, reference commit messages that address the issue in your fixes.

**Comment by nicoandrade** [comment]
Sorry, will do.

**Comment by cristianraiber** [comment]
@giucu91 - please make sure this has been implemented.

**Comment by cristianraiber** [comment]
@giucu91 - while this works, please make sure that all the default image paths are correct. The main header image path isn't correct.
