### ISSUE TITLE
Getting started section 3 rows steps broken

### ISSUE THREAD

**Issue by razvanaldea89** [puikinsh/bonkers#27]
![bonkers 3 rows](https://user-images.githubusercontent.com/44024114/63677785-71677a80-c7f6-11e9-8d10-f6a7653ae83b.PNG)

**Comment by mahendrapratap4022** [comment]
Hi, I checked it's fine can you be more specific with giving bug description in details.

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/121292984-893cbf80-c8f3-11eb-810f-27bfcffee44a.png)

Seems to be fixed now, was talking about the 3 columns ( not rows, sorry ) with the steps
