### ISSUE TITLE
Easy 1-click theme setup bug

### ISSUE THREAD

**Issue by razvanaldea89** [puikinsh/bonkers#28]
If I install the recommended plugins manually, the `Easy 1-click theme setup` won't work, clicking the button does nothing.

**Comment by mahendrapratap4022** [comment]
Hi, I checked it's working on my end I installed plugins manually and then click on `Easy 1-click theme setup` button and it worked demo data successfully imported. It would be great if you can share a screenshot of the bug.

**Comment by razvanaldea89** [comment]
Seems to be fixed now
