### ISSUE TITLE
Theme doesn't explain what you have to do to get front-page layout

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#3]
There's zero indication that you have to set a static front-page and add select a template for the front-page as well. Not all users are tech savvy :)

**Comment by nicoandrade** [comment]
I expected that to be on the documentation. But I will add it on the Readme.

**Comment by cristianraiber** [comment]
@nicoandrade - you should look into adding this: https://github.com/justintadlock/trt-customizer-pro inside the theme. We've used in the following theme: https://github.com/puikinsh/shapely to add a 'Documentation' button in the Customizer panel. Very visible for the user.

**Comment by nicoandrade** [comment]
I'm not sure that this is the case for such a small thing like the help on the readme file.
