### ISSUE TITLE
No quick edit shortcuts

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#5]
![image](https://user-images.githubusercontent.com/7841556/30125678-dead09de-9341-11e7-89a0-7637fa14172f.png)

---

Just to be clear, I'm referring to the circled pencil icon. Screenshot above is taken from MedZone. Bonkers doesn't have any.

**Comment by cristianraiber** [comment]
@nicoandrade - will this be implemented?

**Comment by nicoandrade** [comment]
No, this will not be implemented.

**Comment by cristianraiber** [comment]
@nicoandrade - ok, thanks; we'll handle it from here.
