### ISSUE TITLE
Clicking on add new services takes me to widget page, no way to get back ... ?

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#6]
![image](https://user-images.githubusercontent.com/7841556/30125717-048bba2e-9342-11e7-93b1-e4f6d2cb966d.png)

---

If you're providing navigation inside Customizer panels, you might as well make the user's life easier and provide a way back, after he's finished adding content.

**Comment by nicoandrade** [comment]
Also here I don't think this is necessary.

**Comment by cristianraiber** [comment]
I wouldn't be asking if it wouldn't be necessary. This is a feature half-implemented right now. Please fix this.

**Comment by nicoandrade** [comment]
I think there is a confusion here. This supposed to be a review like the WP.org repo. Not a enhancement suggestion.
