### ISSUE TITLE
Global 'background-colors' can be overwritten from section

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#7]
Colors -> Background color -> set to `#FFF`
Front-page Sections -> Phone -> Background color -> set to `#1e73be`

This is a bit of a weird behavior. Usually, the general color panels overwrites the individual panel controls. Not saying it's broken, it's just the other way around.

**Comment by nicoandrade** [comment]
Is intended. I think the panels should overwrites the global backgorund, since each module are a separate part of design that may or may not match the global background.

**Comment by cristianraiber** [comment]
Ok, if it was intended.
