### ISSUE TITLE
Adding text inside Textarea from Front-page Sections -> Video doesn't show up on front-end

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#8]
![image](https://user-images.githubusercontent.com/7841556/30125845-7f4a485c-9342-11e7-8829-b25387a8687a.png)

Also, TinyMCE instances could/should be used here. They're more friendly to the user as well as help control the type of output the user is expected to see.

**Comment by nicoandrade** [comment]
Fixed

**Comment by cristianraiber** [comment]
Works as advertised.
