### ISSUE TITLE
Adding text inside Front-Page Sections -> Subscribe Textarea doesn't show up on front-page

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/bonkers#9]
![image](https://user-images.githubusercontent.com/7841556/30163009-0d233a14-938c-11e7-81f1-efbc1384388a.png)

---

There's also the problem that the subscribe form's integrated only with JetPack. If that's the only reason you're recommending JetPack, I'd advise into looking working with MailChimp's API as it only requires a few text inputs to connect to the service.

**Comment by nicoandrade** [comment]
Fixed

**Comment by cristianraiber** [comment]
Works as advertised.
